### ISSUE TITLE
refactor: 데모데이 이전 코드 전반적 리팩토링

### ISSUE THREAD

**Issue by leeeeeyeon** [TeamDilly/Packy-Server#199]
### 💼 작업 설명

데모데이를 성공적으로 마무리하며 패키의 1차 프로젝트가 완료되었습니다. 
다음 개발에 들어가기 이전에 그동안 작성한 코드를 전반적으로 리팩토링합니다.
아래 레퍼런스에 리팩토링에 관련한 좋은 포스트가 많이 있어 참고하면 좋을 것 같습니다 :)

Reference: https://jaehoney.tistory.com/category/Programming/Refactoring

### ✅ To-do

- [ ] 의존성 사이클 검사 및 개선
- [ ] DTO를 inner static class로 관리
- [ ] 가독성이 좋지 않은 테스트 코드 다시 작성
- [ ] (추후 더 추가하기 ...)
