### ISSUE TITLE
feat: 웹용 선물박스 열기 API 구현

### ISSUE THREAD

**Issue by leeeeeyeon** [TeamDilly/Packy-Server#214]
### 💼 작업 설명

웹에서 사용할 선물박스 열기 API를 구현합니다.

### ✅ To-do

- [x] 웹용 선물박스 열기 API 구현
  - [x] 선물박스를 보낸지 7일이 지나면 선물박스를 열 수 없어야 한다
  - [x] 토큰이 없는 상태에서 API 접근이 가능해야 한다
- [x] CORS 문제 해결
