### ISSUE TITLE
setting: common 모듈 생성

### ISSUE THREAD

**Issue by leeeeeyeon** [TeamDilly/Packy-Server#60]
### 💼 작업 설명

infra 모듈에 있는 외부 API 연동 클래스가 커스텀 예외를 처리할 수 있도록 합니다.
api 모듈의 global 패키지에 있는 exception 패키지를 common 모듈로 이동시키고, api 모듈과 infra 모듈이 common 모듈을 의존하도록 합니다.

### ✅ To-do

- [x] common 모듈 생성
- [x] exception 패키지를 common 모듈로 옮기기
- [x] api 모듈에 common 모듈 의존성 주입
- [x] appleService, kakaoService를 infra 모듈로 옮기기
